In [ ]:
#Tensors
import torch


In [ ]:
#1D 0 tensor
x = torch.empty(3)
print(x)

tensor([1.4534e-35, 0.0000e+00, 3.3631e-44])


In [ ]:
#2D empty tensor
x = torch.empty(2,3)
print(x)

tensor([[1.4534e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [ ]:
#4D empty tensor
x = torch.empty(2,2,1,5)


In [ ]:
x = torch.rand(2,3)
print(x)

tensor([[0.0309, 0.2578, 0.4639],
        [0.1590, 0.8325, 0.8164]])


In [ ]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(x.dtype)

torch.float32


In [ ]:
x = torch.ones(2,3, dtype = torch.float16)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)


In [ ]:
x = torch.tensor([2.5, 0.1])

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.9273, 0.8087],
        [0.1758, 0.4616]])
tensor([[0.9147, 0.7566],
        [0.4322, 0.4772]])


In [ ]:
z = x + y
print(z)

tensor([[1.8421, 1.5653],
        [0.6080, 0.9389]])


In [ ]:
y.add_(x)
print(y)

tensor([[1.8421, 1.5653],
        [0.6080, 0.9389]])


In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])

tensor([[0.7588, 0.0215, 0.6310],
        [0.4863, 0.3608, 0.4705],
        [0.5291, 0.9748, 0.5433],
        [0.4844, 0.0612, 0.6503],
        [0.1149, 0.1005, 0.2327]])
tensor([0.7588, 0.4863, 0.5291, 0.4844, 0.1149])
tensor([0.4863, 0.3608, 0.4705])


In [ ]:
x = torch.rand(4,4)
print(x)
y = x.view(-1, 8)
print(y)

tensor([[0.1678, 0.4111, 0.3866, 0.8538],
        [0.0203, 0.5153, 0.7419, 0.0820],
        [0.8530, 0.5688, 0.8711, 0.3687],
        [0.1244, 0.7967, 0.8747, 0.6926]])
tensor([[0.1678, 0.4111, 0.3866, 0.8538, 0.0203, 0.5153, 0.7419, 0.0820],
        [0.8530, 0.5688, 0.8711, 0.3687, 0.1244, 0.7967, 0.8747, 0.6926]])


In [ ]:
import numpy as np
a = torch.ones(5)

In [ ]:
b = a.numpy()
type(b)

numpy.ndarray

In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available() == False:
  print(x)

tensor([[0.1678, 0.4111, 0.3866, 0.8538],
        [0.0203, 0.5153, 0.7419, 0.0820],
        [0.8530, 0.5688, 0.8711, 0.3687],
        [0.1244, 0.7967, 0.8747, 0.6926]])


In [ ]:
device = torch.device("cpu")

In [ ]:
x = torch.ones(5, device = device)
y = torch.ones(5,)
y.to(device)
z = x + y

In [ ]:
z = z.to("cpu")

In [ ]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [ ]:
x = torch.tensor([4.0], requires_grad = True)
y = x**2
y.backward()
print(x.grad)

tensor([8.])


In [ ]:
x = torch.tensor([2.0], requires_grad = True)
y = torch.tensor([1.0], requires_grad = True)

z = x**2 + y**2
z.backward()
print(x.grad, y.grad)

tensor([4.]) tensor([2.])


In [ ]:
x = torch.rand(3, requires_grad = True)
print(x)

y = x + 2
print(y)


tensor([0.4241, 0.1464, 0.7067], requires_grad=True)
tensor([2.4241, 2.1464, 2.7067], grad_fn=<AddBackward0>)


In [ ]:
z = y*y*2
z = z.mean()
print(z)
print(x.grad)

tensor(11.8731, grad_fn=<MeanBackward0>)
None


In [ ]:
v = torch.tensor([0.1 ,1.0, 0.001], dtype = torch.float32)
print(v.grad)

None


In [ ]:
z = y*y*2
print(z.backward(v))
x.grad

None


tensor([0.9697, 8.5857, 0.0108])

In [ ]:
x.requires_grad_(False)

tensor([0.4241, 0.1464, 0.7067])

In [ ]:
w = x.detach()
print(y)

tensor([2.4241, 2.1464, 2.7067], grad_fn=<AddBackward0>)


In [ ]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([2.4241, 2.1464, 2.7067])


In [ ]:
weights = torch.ones(4, requires_grad = True)
for iterate in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_() #empty gradients

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
#backpropagation
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)
#forward pass
y_hat = w*x
loss = (y_hat - y)**2
print(loss)

#backward pass
loss.backward()
print(w.grad)

#update weights

#

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [ ]:
X = np.array([1,2,3,4], dtype = np.float32)
Y = np.array([2,4,6,8], dtype = np.float32)
def f(x):
  return 2*x
w = 0.0

#model prediction

def forward(x):
  return w*x
print(forward(X))
def loss(y, y_predicted):
  return ((y - y_predicted)**2).mean()

def gradient(x, y, y_predicted):
  return np.dot(2*x, y_predicted - y).mean()

learning_rate = 0.01

n_iters = 20

for epoch in range(n_iters):
  y_pred  = forward(X)
  l = loss(Y, y_pred)
  dw = gradient(X, Y, y_pred)
  w-= learning_rate*dw

  if epoch % 1 == 0:
    print(w,"   ", l)
print(f(5))

[0. 0. 0. 0.]
1.2     30.0
1.6799999618530272     4.799999
1.871999988555908     0.7680002
1.9487999868392942     0.12288
1.9795200133323667     0.019660834
1.9918080282211301     0.0031457357
1.9967231869697568     0.000503308
1.99868928194046     8.053186e-05
1.999475698471069     1.2884395e-05
1.999790253639221     2.0613531e-06
1.9999160599708554     3.29734e-07
1.9999664139747617     5.2823452e-08
1.9999865984916685     8.487817e-09
1.9999946093559262     1.3369572e-09
1.9999978351593015     2.1679014e-10
1.9999991369247434     3.5313974e-11
1.9999996304512022     5.076828e-12
1.999999837875366     8.9883656e-13
1.9999999165534972     1.314504e-13
1.9999999952316283     1.314504e-13
10


In [ ]:
X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)
w = torch.tensor(0.0, dtype = torch.float32, requires_grad = True)

#model prediction

def forward(x):
  return w*x
def loss(y, y_predicted):
  return ((y - y_predicted)**2).mean()



learning_rate = 0.01

n_iters = 100

for epoch in range(n_iters):
  y_pred  = forward (X)
  l = loss(Y, y_pred)
  dw = l.backward()
  with torch.no_grad():
  #dw = gradient(X, Y, y_pred)
    w-= learning_rate*w.grad
  w.grad.zero_()
  if epoch % 10 == 0:
    print(w, l)



tensor(0.3000, requires_grad=True) tensor(30., grad_fn=<MeanBackward0>)
tensor(1.6653, requires_grad=True) tensor(1.1628, grad_fn=<MeanBackward0>)
tensor(1.9341, requires_grad=True) tensor(0.0451, grad_fn=<MeanBackward0>)
tensor(1.9870, requires_grad=True) tensor(0.0017, grad_fn=<MeanBackward0>)
tensor(1.9974, requires_grad=True) tensor(6.7705e-05, grad_fn=<MeanBackward0>)
tensor(1.9995, requires_grad=True) tensor(2.6244e-06, grad_fn=<MeanBackward0>)
tensor(1.9999, requires_grad=True) tensor(1.0176e-07, grad_fn=<MeanBackward0>)
tensor(2.0000, requires_grad=True) tensor(3.9742e-09, grad_fn=<MeanBackward0>)
tensor(2.0000, requires_grad=True) tensor(1.4670e-10, grad_fn=<MeanBackward0>)
tensor(2.0000, requires_grad=True) tensor(5.0768e-12, grad_fn=<MeanBackward0>)


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

num_epochs = 4
batch_size = 4
learning_rate = 0.001



transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))])


train_dataset = torchvision.datasets.CIFAR10(root = '/data', train = True, download = True, transform = transform)
test_dataset = torchvision.datasets.CIFAR10(root = '/data', train = False, download = True, transform = transform)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size = batch_size, shuffle = False)


classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck'
)

class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16*5*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

model = ConvNet().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

n_total_steps = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 2000 == 0:
            print((epoch+1/num_epochs), ((i+1)/n_total_steps), loss.item)
print('Finished')

with torch.no_grad():
    n_correct = 0
    n_samples = 0
    n_class_correct = [0 for i in range(10)]
    n_class_samples = [0 for i in range(10)]
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = model(images)
        
        
        _, predicted = torch.max(outputs, 1)
        n_samples += labels.size(0)
        n_correct += (predicted == labels).sum().item()
        
        for i in range(batch_size):
            label = labels[i]
            pred = predicted[i]
            if (label == pred):
                n_class_correct[label] += 1
            n_class_samples[label] += 1


  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting /data/cifar-10-python.tar.gz to /data
Files already downloaded and verified
0.25 0.16 <built-in method item of Tensor object at 0x7f32ddb2d590>
0.25 0.32 <built-in method item of Tensor object at 0x7f32ddb2d1d0>
0.25 0.48 <built-in method item of Tensor object at 0x7f32ddb2d890>
0.25 0.64 <built-in method item of Tensor object at 0x7f32ddb2d4d0>
0.25 0.8 <built-in method item of Tensor object at 0x7f32ddb2d1d0>
0.25 0.96 <built-in method item of Tensor object at 0x7f32ddb2d650>
1.25 0.16 <built-in method item of Tensor object at 0x7f32ddb2d890>
1.25 0.32 <built-in method item of Tensor object at 0x7f32ddb2d590>
1.25 0.48 <built-in method item of Tensor object at 0x7f32ddb2d290>
1.25 0.64 <built-in method item of Tensor object at 0x7f32ddb2d290>
1.25 0.8 <built-in method item of Tensor object at 0x7f32ddb2d1d0>
1.25 0.96 <built-in method item of Tensor object at 0x7f32ddb2d5f0>
2.25 0.16 <built-in method item of Tensor object at 0x7f32ddb2d530>
2.25 0.32 <built-in method item